apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-app
spec:
  replicas: {{ .Values.book.replicaCount}}
  selector:
    matchLabels:
      app: book-app
  template:
    metadata:
      labels:
        app: book-app
    spec:
      containers:
      - name: book-app
        image: {{ .Values.book.container.image}}
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: {{ .Values.book.port}}
        envFrom:
          - configMapRef:
              name: book-app-config
          - secretRef:
              name: book-postgres-secret