apiVersion: v1
kind: Secret
metadata:
  name: book-postgres-secret
type: Opaque
stringData:
  DB_HOST: app-bookdb
  DB_DRIVER: postgres
  DB_USERNAME: {{ .Values.bookdb.auth.username }}
  DB_PASSWORD: {{ .Values.bookdb.auth.password }}
  DB_DBNAME: {{ .Values.bookdb.auth.database }}
  DB_PORT: "5432"