apiVersion: v1
kind: Secret
metadata:
  name: delivery-postgres-secret
type: Opaque
stringData:
  DB_HOST: app-deliverydb
  DB_DRIVER: postgres
  DB_USERNAME: {{ .Values.deliverydb.auth.username }}
  DB_PASSWORD: {{ .Values.deliverydb.auth.password }}
  DB_DBNAME: {{ .Values.deliverydb.auth.database }}
  DB_PORT: "5432"