apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-app
spec:
  replicas: {{ .Values.store.replicaCount}}
  selector:
    matchLabels:
      app: store-app
  template:
    metadata:
      labels:
        app: store-app
    spec:
      containers:
      - name: store-app
        image: {{ .Values.store.container.image}}
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: {{ .Values.store.port}}
        envFrom:
          - configMapRef:
              name: store-app-config
          - secretRef:
              name: store-postgres-secret