apiVersion: v1
kind: Secret
metadata:
  name: store-postgres-secret
type: Opaque
stringData:
  DB_HOST: app-storedb
  DB_DRIVER: postgres
  DB_USERNAME: {{ .Values.storedb.auth.username }}
  DB_PASSWORD: {{ .Values.storedb.auth.password }}
  DB_DBNAME: {{ .Values.storedb.auth.database }}
  DB_PORT: "5432"