apiVersion: v1
kind: Service
metadata:
  name: store-app
  labels:
    app: store-app
spec:
  selector:
    app: store-app
  ports:
    - name: web
      port: 80
      targetPort: {{ .Values.store.port}}
  type: ClusterIP
