apiVersion: v1
kind: Secret
metadata:
  name: payment-postgres-secret
type: Opaque
stringData:
  DB_HOST: app-paymentdb
  DB_DRIVER: postgres
  DB_USERNAME: {{ .Values.paymentdb.auth.username }}
  DB_PASSWORD: {{ .Values.paymentdb.auth.password }}
  DB_DBNAME: {{ .Values.paymentdb.auth.database }}
  DB_PORT: "5432"