apiVersion: v1
kind: Service
metadata:
  name: payment-app
  labels:
    app: payment-app
spec:
  selector:
    app: payment-app
  ports:
    - name: web
      port: 80
      targetPort: {{ .Values.payment.port}}
  type: ClusterIP
