apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app
spec:
  replicas: {{ .Values.order.replicaCount}}
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      labels:
        app: order-app
    spec:
      containers:
      - name: order-app
        image: {{ .Values.order.container.image}}
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: {{ .Values.order.port}}
        envFrom:
          - configMapRef:
              name: order-app-config
          - secretRef:
              name: order-postgres-secret