apiVersion: v1
kind: Secret
metadata:
  name: order-postgres-secret
type: Opaque
stringData:
  DB_HOST: app-orderdb
  DB_DRIVER: postgres
  DB_USERNAME: {{ .Values.orderdb.auth.username }}
  DB_PASSWORD: {{ .Values.orderdb.auth.password }}
  DB_DBNAME: {{ .Values.orderdb.auth.database }}
  DB_PORT: "5432"