apiVersion: v1
kind: Service
metadata:
  name: order-app
  labels:
    app: order-app
spec:
  selector:
    app: order-app
  ports:
    - name: web
      port: 80
      targetPort: {{ .Values.order.port}}
  type: ClusterIP
