port: "8000"

db:
    username: "postgres"
    host: "localhost"
    port: "5432"
    dbname: "postgres"
    password: "manager"

kafka:
    ORDER_CREATED_TOPIC: order_created_v1

api:
    StoreURI: "http://arch.homework:8004/store"
    PaymentURI: "http://arch.homework:8005/payment"
    BookURI: "http://arch.homework:8002/book"